- name: Run Example Jenkins
  hosts: all
  sudo: yes
  tasks:
    - name: ensure Tomcat is at the latest version
      apt: name=tomcat7 state=latest update_cache=yes

    - name: ensure Tomcat is stopped
      service: name=tomcat7 state=stopped

    - name: download Jenkins
      get_url: url="https://updates.jenkins-ci.org/download/war/1.549/jenkins.war" dest=/tmp/jenkins.war mode=0644

    - name: "Create the /var/lib/jenkins directory"
      file: path=/var/lib/jenkins/ owner=tomcat7 group=tomcat7 mode=0777 state=directory

    - name: "Create the Home directory"
      file: path=/usr/share/tomcat7/.jenkins owner=tomcat7 group=tomcat7 mode=0777 state=directory

    - name: Upload Jenkins to host
      copy: >
          src=/tmp/jenkins.war
          dest=/var/lib/tomcat7/webapps/jenkins.war
          mode=0644

    - name: start Tomcat to pickup and install Jenkins
      service: name=tomcat7 state=started

