- name: Run Example Jenkins
  hosts: all
  sudo: yes
  tasks:
    - name: ensure Tomcat is at the latest version
      apt: name=tomcat7 state=latest

    - name: ensure Tomcat is stopped
      service: name=Tomcat state=stopped

    - name: download Jenkins
      get_url: url="http://mirrors.Jenkins-ci.org/war/1.549/Jenkins.war" dest=/tmp/Jenkins.war mode=0644

    - name: "Create the /var/lib/Jenkins directory"
      file: path=/var/lib/Jenkins/ owner=tomcat group=tomcat mode=0777 state=directory

    - name: Upload Jenkins to host
      copy: >
          src=/tmp/Jenkins.war
          dest=/usr/share/Tomcat/webapps/Jenkins.war
          mode=0644
    - name: start Tomcat to pickup and install Jenkins
      service: name=Tomcat state=started

    - wait_for: path=/var/lib/Jenkins/plugins/
