---

- name: Nginx | Install nginx
  sudo: yes
  apt: pkg=nginx
  tags: nginx

- name: Nginx | Setup reverse proxy
  sudo: yes
  template: src=nginx_site_config.j2 dest=/etc/nginx/sites-available/
  tags: nginx

- name: Nginx | Start nginx
  sudo: yes
  service: name=nginx state=restarted
  tags: nginx
